sudo: false
language: ruby
rvm:
  - 2.3.3
before_install:
  - docker-compose pull
  - docker-compose build
  - docker-compose create
  - docker-compose start
install:
  - travis_retry bundle install
script: rspec
