version: '2'
services:
  mysql:
    image: mysql:5.7
    command: mysqld
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=''
  zookeeper:
    image: "wurstmeister/zookeeper"
    ports:
      - 2181:2181
  kafka:
    image: "wurstmeister/kafka:0.11.0.1"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_DELETE_TOPIC_ENABLE=true
    ports:
      - 9092:9092

